"""A reversible value adapter from typed traces to upstream ASP facts."""

from __future__ import annotations

import base64
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from pydantic import JsonValue

from .io import canonical_json
from .models import TraceDataset, json_compatible

PARAM_ENCODING = "canonical-json-base64url-v1"
_PARAM_PREFIX = "json_b64:"


@dataclass(frozen=True)
class AspTraceBundle:
    """Generated facts plus a deep-copy snapshot of their typed source."""

    facts: str
    source: TraceDataset
    source_sha256: str
    parameter_encoding: str = PARAM_ENCODING

    def write(self, path: str | Path) -> None:
        Path(path).write_text(self.facts, encoding="utf-8")


def encode_json_value(value: JsonValue) -> str:
    """Encode a JSON value into one ASP string without erasing its type."""

    canonical = json.dumps(
        json_compatible(value),
        ensure_ascii=False,
        allow_nan=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    encoded = base64.urlsafe_b64encode(canonical).decode("ascii")
    return _PARAM_PREFIX + encoded


def decode_json_value(value: str) -> JsonValue:
    if not value.startswith(_PARAM_PREFIX):
        raise ValueError(f"unsupported ASP parameter encoding: {value!r}")
    encoded = value.removeprefix(_PARAM_PREFIX)
    try:
        raw = base64.b64decode(encoded, altchars=b"-_", validate=True)
        decoded = json.loads(raw.decode("utf-8"))
    except (ValueError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError("invalid canonical-json-base64url-v1 value") from exc
    return json_compatible(decoded)


def _asp_string(value: str) -> str:
    """Quote normal UTF-8 identifiers using Clingo-compatible escapes."""

    return json.dumps(value, ensure_ascii=False)


def to_asp(dataset: TraceDataset) -> AspTraceBundle:
    """Adapt the upstream-supported subset while retaining the typed source."""

    source = dataset.model_copy(deep=True)
    source_json = canonical_json(source)
    lines = [
        "% Generated by Trace2Flow's typed ASP adapter.",
        f"% schema_version={source.schema_version}",
        f"% parameter_encoding={PARAM_ENCODING}",
        "% The normalized JSON source remains authoritative.",
        "#defined job/1.",
        "#defined job_status/2.",
        "#defined call/4.",
        "#defined depends/3.",
        "#defined spawned_by/3.",
        "#defined param/4.",
        "",
    ]

    for run in source.runs:
        run_id = _asp_string(run.id)
        lines.append(f"job({run_id}).")
        lines.append(f"job_status({run_id}, {_asp_string(run.status.value)}).")
        for step in run.steps:
            step_id = _asp_string(step.id)
            lines.append(
                f"call({run_id}, {step_id}, {_asp_string(step.tool)}, "
                f"{_asp_string(step.status.value)})."
            )
            for dependency_id in step.depends_on:
                lines.append(
                    f"depends({run_id}, {step_id}, {_asp_string(dependency_id)})."
                )
            if step.spawned_by is not None:
                lines.append(
                    f"spawned_by({run_id}, {step_id}, "
                    f"{_asp_string(step.spawned_by)})."
                )
            for key in sorted(step.params):
                encoded = encode_json_value(step.params[key])
                lines.append(
                    f"param({run_id}, {step_id}, {_asp_string(key)}, "
                    f"{_asp_string(encoded)})."
                )
        lines.append("")

    return AspTraceBundle(
        facts="\n".join(lines).rstrip() + "\n",
        source=source,
        source_sha256=hashlib.sha256(source_json.encode("utf-8")).hexdigest(),
    )
