"""Deterministic and gated Prefect source generation from Workflow IR."""

from __future__ import annotations

import ast
import hashlib
import pprint
from dataclasses import dataclass
from pathlib import Path

from .ir import ConstantBinding, TaskInputBinding, ToolOutputBinding, WorkflowIR


class PrefectExportError(ValueError):
    """The workflow cannot be safely exported to Prefect."""


@dataclass(frozen=True)
class PrefectArtifact:
    source: str
    source_sha256: str
    required_tools: tuple[str, ...]

    def write(self, path: str | Path) -> None:
        Path(path).write_text(self.source, encoding="utf-8")


def _literal(value: object) -> str:
    return pprint.pformat(value, width=88, sort_dicts=True)


def _topological_nodes(workflow: WorkflowIR):
    nodes = {node.id: node for node in workflow.nodes}
    predecessors: dict[str, set[str]] = {node_id: set() for node_id in nodes}
    for edge in workflow.edges:
        predecessors[edge.target_node_id].add(edge.source_node_id)
    remaining = set(nodes)
    ordered = []
    while remaining:
        ready = sorted(
            node_id
            for node_id in remaining
            if predecessors[node_id].isdisjoint(remaining)
        )
        if not ready:
            raise PrefectExportError("workflow contains a cycle")
        for node_id in ready:
            ordered.append(nodes[node_id])
            remaining.remove(node_id)
    return ordered


def export_prefect(
    workflow: WorkflowIR,
    registered_tools: set[str] | frozenset[str],
) -> PrefectArtifact:
    """Generate source only after all execution and registry gates pass."""

    blockers = workflow.execution_blockers()
    if blockers:
        raise PrefectExportError(
            "workflow is not executable:\n- " + "\n- ".join(blockers)
        )
    required_tools = tuple(sorted({node.tool for node in workflow.nodes}))
    unknown_tools = sorted(set(required_tools) - set(registered_tools))
    if unknown_tools:
        raise PrefectExportError(
            "workflow contains unregistered tool(s): " + ", ".join(unknown_tools)
        )

    ordered_nodes = _topological_nodes(workflow)
    outgoing = {node.id: set() for node in workflow.nodes}
    for edge in workflow.edges:
        outgoing[edge.source_node_id].add(edge.target_node_id)
    sink_ids = sorted(node_id for node_id, targets in outgoing.items() if not targets)
    if not sink_ids:
        final_expression = "None"
    elif len(sink_ids) == 1:
        final_expression = f"outputs[{_literal(sink_ids[0])}]"
    else:
        entries = ", ".join(
            f"{_literal(node_id)}: outputs[{_literal(node_id)}]"
            for node_id in sink_ids
        )
        final_expression = "{" + entries + "}"

    lines = [
        '"""Generated by Trace2Flow from validated Workflow IR; do not hand-edit."""',
        "",
        "from __future__ import annotations",
        "",
        "from prefect import flow, task",
        "",
        "from trace2flow.runtime import ToolRegistry, get_path",
        "",
        f"REQUIRED_TOOLS = {_literal(required_tools)}",
        f"WORKFLOW_ID = {_literal(workflow.workflow_id)}",
        "",
        '@task(name="trace2flow-registered-tool")',
        "def _invoke_registered(",
        "    registry: ToolRegistry, tool_name: str, params: dict[str, object]",
        ") -> object:",
        "    return registry.invoke(tool_name, params)",
        "",
        "@flow(name=WORKFLOW_ID, validate_parameters=False, persist_result=False)",
        "def run_workflow(",
        "    task_input: dict[str, object], registry: ToolRegistry",
        ") -> dict[str, object]:",
        "    if not set(REQUIRED_TOOLS).issubset(registry.names):",
        "        missing = sorted(set(REQUIRED_TOOLS) - registry.names)",
        '        raise ValueError("missing registered tool(s): " + ", ".join(missing))',
        "    outputs: dict[str, object] = {}",
    ]
    for index, node in enumerate(ordered_nodes):
        params_name = f"params_{index}"
        lines.append(f"    {params_name}: dict[str, object] = {{}}")
        for parameter, binding in sorted(node.parameters.items()):
            if isinstance(binding, ConstantBinding):
                expression = _literal(binding.value)
            elif isinstance(binding, TaskInputBinding):
                expression = f"get_path(task_input, {_literal(binding.path)})"
            elif isinstance(binding, ToolOutputBinding):
                expression = (
                    f"get_path(outputs[{_literal(binding.source_node_id)}], "
                    f"{_literal(binding.path)})"
                )
            else:  # pragma: no cover - guarded by execution_blockers
                raise PrefectExportError(
                    f"parameter '{node.id}.{parameter}' is not exportable"
                )
            lines.append(f"    {params_name}[{_literal(parameter)}] = {expression}")
        lines.append(
            f"    outputs[{_literal(node.id)}] = _invoke_registered("
            f"registry, {_literal(node.tool)}, {params_name})"
        )
    lines.extend(
        [
            "    return {",
            '        "workflow_id": WORKFLOW_ID,',
            '        "outputs": outputs,',
            f'        "final_output": {final_expression},',
            "    }",
            "",
        ]
    )
    source = "\n".join(lines)
    ast.parse(source)
    return PrefectArtifact(
        source=source,
        source_sha256=hashlib.sha256(source.encode()).hexdigest(),
        required_tools=required_tools,
    )
