"""Generated by Trace2Flow from validated Workflow IR; do not hand-edit."""

from __future__ import annotations

from prefect import flow, task

from trace2flow.runtime import ToolRegistry, get_path

REQUIRED_TOOLS = ('classify_issue',
 'lookup_customer',
 'lookup_order',
 'recommend_action',
 'update_ticket')
WORKFLOW_ID = 'agent-corpus-v1-compile-workflow'

@task(name="trace2flow-registered-tool")
def _invoke_registered(
    registry: ToolRegistry, tool_name: str, params: dict[str, object]
) -> object:
    return registry.invoke(tool_name, params)

@flow(name=WORKFLOW_ID, validate_parameters=False, persist_result=False)
def run_workflow(
    task_input: dict[str, object], registry: ToolRegistry
) -> dict[str, object]:
    if not set(REQUIRED_TOOLS).issubset(registry.names):
        missing = sorted(set(REQUIRED_TOOLS) - registry.names)
        raise ValueError("missing registered tool(s): " + ", ".join(missing))
    outputs: dict[str, object] = {}
    params_0: dict[str, object] = {}
    params_0['customer_id'] = get_path(task_input, ['customer_id'])
    params_0['order_id'] = get_path(task_input, ['order_id'])
    outputs['node_04ec0affeb6e'] = _invoke_registered(registry, 'lookup_order', params_0)
    params_1: dict[str, object] = {}
    params_1['customer_id'] = get_path(task_input, ['customer_id'])
    outputs['node_a7583bb9c049'] = _invoke_registered(registry, 'lookup_customer', params_1)
    params_2: dict[str, object] = {}
    params_2['damaged'] = get_path(outputs['node_04ec0affeb6e'], ['damaged'])
    params_2['delivered'] = get_path(outputs['node_04ec0affeb6e'], ['delivered'])
    params_2['duplicate_charge'] = get_path(outputs['node_04ec0affeb6e'], ['duplicate_charge'])
    params_2['order_status'] = get_path(outputs['node_04ec0affeb6e'], ['status'])
    params_2['ticket_text'] = get_path(task_input, ['ticket_text'])
    outputs['node_0d9843881654'] = _invoke_registered(registry, 'classify_issue', params_2)
    params_3: dict[str, object] = {}
    params_3['eligible'] = get_path(outputs['node_0d9843881654'], ['eligible'])
    params_3['issue_type'] = get_path(outputs['node_0d9843881654'], ['issue_type'])
    params_3['policy_version'] = get_path(task_input, ['policy_version'])
    outputs['node_7d752d73063d'] = _invoke_registered(registry, 'recommend_action', params_3)
    params_4: dict[str, object] = {}
    params_4['issue_type'] = get_path(outputs['node_7d752d73063d'], ['issue_type'])
    params_4['recommendation'] = get_path(outputs['node_7d752d73063d'], ['recommendation'])
    params_4['status'] = get_path(outputs['node_7d752d73063d'], ['status'])
    params_4['ticket_id'] = get_path(task_input, ['ticket_id'])
    outputs['node_034187e584c6'] = _invoke_registered(registry, 'update_ticket', params_4)
    return {
        "workflow_id": WORKFLOW_ID,
        "outputs": outputs,
        "final_output": outputs['node_034187e584c6'],
    }
